version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nest:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${APP_PORT}
    depends_on:
      - db
    volumes:
      - ./src/:/app/src/
      - /app/node_modules
