version: '3'

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    # environment:
    #   - DB_TYPE=${DB_TYPE}
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_SYNC=false
    #   - JWT_SECRET=${JWT_SECRET}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    #   - APP_PORT=${APP_PORT}
    depends_on:
      - db
    volumes:
      - ./src/:/app/src/
      - /app/node_modules
  db:
    image: postgres
    restart: always
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSRGRES_HOST=postgres
    container_name: postgres
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'
